### ISSUE TITLE
Suggesting increased granularity of the filter criteria

### ISSUE THREAD

**Issue by romykl** [eyalroz/removedupes#112]
I would like to suggest to increase the granularity of the filtering criteria. This is what I mean:
at the moment there is the filter criteria of "sending time" of the mails. I would suggest to split it finer in separate criteria of "date" and separately from it the "time". Also it should be possible to set the search "time window" of similarity to a limited time from minutes to for example one hour. Reason: I had the case of duplicates which were the same but due to summer/winter time shift had the same time but shifted by one hour. Using the present global settings these cannot be detected, because of too different times, although they are the same only exactly one hour apart. So it is a kind of suggestion for a feature extension.

**Comment by eyalroz** [comment]
This is already mostly-supported: You can choose a time comparison resolution in the extension's preferences dialog.

Do you find that insufficient?

Note that comparing based on time difference is problematic, because if you have three messages at times T, T + d, T + 2*d - then for a window of 1.5d you will get either the first two as dupes, or the second two, but not all three - while being a duplicate needs to be a transitive relation, to form equivalence classes (= dupe sets).

**Comment by romykl** [comment]
Yes, I do. The time comparison resolution should separate date and time in separate filter criteria fields. That way it is easier to find  and recognize optically mails which suffer from the summer/winter time difference mentioned. At the mnoment the two are unified in one common field and thuis make it more difficult to see them at once in the dupes list.
Regarding the time window, that was why I suggested to allow setting this time window flexible acc. to the particular needs created by time shifts of the dupes concerned.

**Comment by eyalroz** [comment]
I don't agree that the use case you suggest justifies breaking up the date-time field. If there are additional requests for this, I'll reconsider.
