### ISSUE TITLE
Not sure if this is problem with removedups or TB. After deleting duplicates on local, the original email is deleted from the POP server

### ISSUE THREAD

**Issue by TomfromTampa** [eyalroz/removedupes#114]
As indicated above, I'm not sure if this is an issue with the removedupes add on or with TB, but when I did a test delete of a couple of duplicate emails from my Thunderbird mailbox, the one and only original email was deleted from the POP server. The only dups were on Thunderbird, so it doesn't seem correct for the correct original to be deleted from the server. Can you tell me your opinion of whether this is:

- An issue with Thunderbird
- An issue with the addon
- User error

**Comment by eyalroz** [comment]
Deleting a message locally can't - in principle - affect what happens on the POP server. Specifically, removedupes doesn't contact the POP server at any point...

However, TB does have settings for deleting messages from POP servers after a given amount of time (in the Account Settings dialog). Could that possibly be what you're seeing?

Otherwise, I would guess it is one of:

1. Problem with the POP server.
2. User error...
3. Weird Thunderbird bug - but this is unlikely, since this can't happen because of a typo.

I'll also mention that nobody has ever complained about this happening to them with the extension.

**Comment by TomfromTampa** [comment]
Thanks for the response. In TB I have the following for deleting messages from the POP server as:
Leave messages on server until I delete them.
Obviously, this is intended to take effect if I specifically delete messages from my TB local repository, and is not intended to delete messages from the server if I delete a duplicate that only exists on my local repository and not on the server. Am I misunderstanding this distinction? Is there a way to get around this?

**Comment by eyalroz** [comment]
To answer your questions:

* About the dialog: The buttons _change_ the selection in the tree view. For example, if you press "last copy", the last item in every set will be selected, and all other items will be de-selected. Now, changing the sort order and choosing first or last copy means you can keep the oldest message or the newest, or the longest, or the shortest, or the one with the lexicographically-first set of recipients etc.

* To only remove duplicates from some of the sets: Press "All Copies"; now manually press the checkmark on those dupes you want to remove. When you've unmarked all undesirable copies, press "Ok", and they will be deleted / moved to trash.

**Comment by eyalroz** [comment]
> I have the following for deleting messages from the POP server as: Leave messages on server until I delete them.

Ah, that would explain things. 

> Obviously, this is intended to take effect if I specifically delete messages from my TB local repository, and is not intended to delete messages from the server if I delete a duplicate that only exists on my local repository and not on the server. Am I misunderstanding this distinction?

Yes, you are. A message is a message, and deleting a local message is supposed to delete it from the POP3 server. The fact that you have downloaded it twice is not something the server is concerned with; and unfortunately, since TB itself does not keep track of double-downloaded - it is supposed to try and delete the original whenever deleting _any_ of the originals.

So, what I suggest you do is:

1. Turn the setting off, i.e. choose to keep messages on the POP3 server indefinitely.
2. Remove dupes.
3. Turn the setting back on, so that when you next manually delete, that would trigger a POP3 server deletion of the copy remaining there.
