### ISSUE TITLE
Not enough arguments for formatStringFromName() when deleting message permanently

### ISSUE THREAD

**Issue by eyalroz** [eyalroz/removedupes#14]
A user reports:

> Since the recent update to removedups (looks like it was pushed on Aug 
> 8, my Thunderbird got it on Aug 11, and I only restarted it last night 
> and noticed the problem) the addon is no longer able to remove duplicate 
> messages with the "Delete Permanently" option. Looking in the error 
> console, it says that that this is because  of the error:
> 
> 
>      NS_ERROR_XPC_NOT_ENOUGH_ARGS: Not enough arguments [nsIStringBundle.formatStringFromName]
> 
> 
> pointing at line 138 of remove-dupes-common.jz. Looking there I see it  
> was modified to remove the final (third) argument to 
> formatStringFromName(), with the comment "The third argument is dropped 
> sometime between TB 68 and TB 78". The problem is that I (like many 
> other people using a distro-built Linux version of Thunderbird rather 
> than an auto-update directly from thunderbird.net) am still running TB 
> 68...

**Comment by lainestump** [comment]
(I am "A User" in the description :-))

Hi Eyal. You had asked in email what version of the addon I'm running. The info page says it is version 0.5b2. When I first noticed the problem, one of the screens told me it had been updated on Aug 11, but now it shows Aug 18, probably because the modification date on the .xpi file was updated when I attempted to fix it myself.

Thanks for the quick response!

**Comment by eyalroz** [comment]
Please try this build:

[removedupes_tbird.xpi.zip](https://github.com/eyalroz/removedupes/files/5092459/removedupes_tbird.xpi.zip)

and let me know if it resolves the issue.

**Comment by lainestump** [comment]
When I tried the build, I saw three small problems, all of them easily solvable:

1) At first it refused to install because it said my Thunderbird version wasn't supported. I solved this by adding in a missing comma between strict_min_version and strict_max_version in manifest.js

2) Once I could get it installed, the "delete duplicates" option didn't show up in the menu as it used to. I saw this error in the debug console, and fixed it by adding the missing parenthesis  at the end of the noted line:

  missing ) in parenthetical removedupes-common.js:140:60

3) Even after fixing the first 2, I still get the same message about "Not enough arguments". After puzzling over this a bit, I *finallly* noticed that the two options for calling formatStringFromName() were swapped from the order they should be in. After swapping those two (so that the newer method of calling the function comes first, and the older version is 2nd), everything once again works as expected! :-)

Thanks again for being so quick to look into this.

**Comment by eyalroz** [comment]
@lainestump I did have those two bugs, but I already fixed those in v0.5b3...

https://github.com/eyalroz/removedupes/blob/development/chrome/content/removedupes-common.js

https://github.com/eyalroz/removedupes/blob/development/manifest.json

Somehow you got the older version of what I'd attached. Sorry about that!
