### ISSUE TITLE
Remove duplicate emails in Thunderbird problem

### ISSUE THREAD

**Issue by AvatarRod** [eyalroz/removedupes#170]
I've successfully used removedupes in Thunderbird for several years but recently, seemingly after a Thunderbird upgrade, I've found the app freezes after being launched and the removedupes activity notification at the bottom shows a _dupe set_ number such as: "Searching for duplicate messages... (refining dupe set 167 of 4576: getting body for message 2 of 2)" but with the _dupe set_ number changing each time the app is used, but with no dulicate emails removed and nothing else happening!

I regularly update Thunderbird which is currently at version 114.0.2 (64 bit).

Please advise how fix can be achieved?

Thanks.

**Comment by eyalroz** [comment]
First, you may want to try the newest beta version, which supports TB v115 (and 114).

Regardless - in the scenario you describe, can you check the Error Console? Do you see entries which mention `removedupes` and seem relevant to the problem?

Otherwise - I'm not quite sure why you would experience this kind of behavior.

**Comment by able2doit** [comment]
I also experience this in TB 102.13.0 on Ubuntu (64-bit).  I've tried tying "repair" the .msf files but no progress.  This is a subfolder within Local Folders (28552 messages).  The Error Console has many entries about "Gloda" not being recognised.

**Comment by eyalroz** [comment]
@able2doit : Please file a separate bug.

@AvatarRod : Reopen if you can answer my question.
