### ISSUE TITLE
v115.0 won't accept "115.0" as the maximum compatible version

### ISSUE THREAD

**Issue by eyalroz** [eyalroz/removedupes#176]
Our maximum compatible version is currently 115.0, but - v115.0 won't accept this!

... we have to bump it up a bit.

**Comment by Giulioski** [comment]
Is there any soul that can bring this plug-in back to life?

thank you

**Comment by eyalroz** [comment]
Please try the latest beta release. It's quite safe, the only remaining problem right now is my inability to add buttons to the toolbar... which is a problem because the TB project refuses to document the changes that they make to critical parts of the app in a way which would allow extension authors to update how _we_ do things (e.g. add a button). Instead, they're trying to coax us into using a limited "WebExtensions API". If you'd like to complain, you can [email the council](mailto:council@thunderbird.net). (Here's a [web page](https://wiki.mozilla.org/Modules/Thunderbird#Thunderbird_Council) about who's on it right now).

**Comment by GVIGVI** [comment]
Can you make the latest add-on beta also compatible with latest thunderbird beta? I am on v119 and cannot install beta add-on. Thanks

**Comment by eyalroz** [comment]
No, because I've never tested my extension with that beta, and don't support any changes to to TB made in it. And those are often breaking changes. I'm still not fully able to support even 115 - only mostly.

If someone were to test and guarantee that nothing is broken between 115 and 119, I could do that I suppose.

**Comment by GVIGVI** [comment]
If you wish, I can test the addon on beta versions and provide feedback. Not an expert but have time and can help if needed. Thanks --Enviado desde mi teléfono Android con GMX Mail. Por favor, disculpe mi brevedad.El 09/10/23, 22:54 Eyal Rozenberg ***@***.***> escribió:

   
  No, because I've never tested my extension with that beta, and don't support any changes to to TB made in it. And those are often breaking changes. I'm still not fully able to support even 115 - only mostly. 
  If someone were to test and guarantee that nothing is broken between 115 and 119, I could do that I suppose.

**Comment by GVIGVI** [comment]
Hi, it is me again. I ran the 0.5.4b5 addon under temporary extensions but TB flags the compatibility error with version 119. I modified the manifest.json file but flags invalid manifest when installed. Replaced the addon directly in the windows folder but TB disables it on startup. Not sure how then to test the 0.5.4b5 addon locally on version 119 :(

**Comment by eyalroz** [comment]
You're not supposed to. I don't support v119. I don't know why it's flagged as invalid - and I won't check. When I have time to work on the extension again - hopefully soon - I have other issues to worry about, relevant to 115. I'm sorry, I just don't have the bandwidth for this.
