### ISSUE TITLE
Handling great amounts of Duplicates.

### ISSUE THREAD

**Issue by JPRuehmann** [eyalroz/removedupes#187]
Because of Problems in Downloading Mail archives I now have Folders with great amounts of Duplicates.
In Extreme for 1 Month 150000 Messages from that are 147000 are duplicates. The Extension only handles about 130 Duplicates per Folder, more gets Thunderbird to crash. Is there some kind of Setting (Timeout or Memory Consumption)? I am using Thunderbird 115 on Linux (Kubuntu 18.04 LTE (32Bit).

**Comment by eyalroz** [comment]
If Thunderbird crashes, the problem can't be with the extension itself, since it only executes "legitimate" actions, or triggers exceptions; this would be a TB bug which you should probably file on bugs.mozilla.org .

Having said that - are you trying to use the review dialog for the duplicates? Because that is likely not a good idea, and even if it didn't crash it would be useless - you would not review 147000 messages manually. So try:

1. Playing with some dupes in a separate folder (with the review dialog)
2. Selecting the right criteria
3. Changing the setting to not-reviewing before moving to trash
4. Applying the removal on the full set of messages

I'll say that the extension easily handles thousands of dupes out of > 150K messages. I've not really tried it with tens of thousands of dupes (and this is the first complaint about it.)

**Comment by JPRuehmann** [comment]
3. first thing I did, I´ve setted it to directly remove because by moving it it does not work anyways (1dup in 3000 Messages).
I wil set a Bug for thunderbird too.

**Comment by JPRuehmann** [comment]
BtW. 130 dups in 12000Messages working fine if it is directly removed, not moved to the Trashcan).

**Comment by JPRuehmann** [comment]
I´ve found a solution.
Run the Process for the Folders you want to clean up. Never mind the crashes simply restart Thunderbird and take the next Folder. After cleaning al the Folders you want delete they´r Index Files and recreate them. Then you should compress them and the duplicates are gone.

**Comment by eyalroz** [comment]
@JPRuehmann : If this works for you, it means TB is crashing while processing the folders, and the extension works fine. You see, I don't delete or move any messages myself: I just tell TB "please move messages XYZ from folder A to folder B".

So, at least for now, I conclude that this is a TB issue and will close. If you disagree, you may reopen, but focus on what you believe I can do.

**Comment by etherija** [comment]
@JPRuehmann I'm having this exact same issue with TB 115 (deleting 10,000s of dupes from 100,000s of emails). Did not have this issue with remove duplicates extension pre 115. What's the Mozilla Bug Report and I will add my request to fix.

If I let remove duplicates finish on large folders (100,000+ emails) it does work, but takes several hours with almost no CPU/IO but almost 100% RAM usage (32GB).
