### ISSUE TITLE
Find duplicates of the same message sent to multiple mailing lists

### ISSUE THREAD

**Issue by RogerRiggs** [eyalroz/removedupes#20]
It would be useful if the same message sent to multiple mailing/distribution lists could be identified for removal.
Perhaps matching on the message subject and contents would be sufficiently unique.

**Comment by eyalroz** [comment]
@RogerRiggs : 

1. What's preventing you from doing that right now?
2. If the mailing list alters the message (adding subject content, adding a header or a footer to the body, formatting etc.) - then it becomes nearly impossible to tell that it was indeed the same message.

**Comment by RogerRiggs** [comment]
It comes down to what attributes are used to determine "same".
In my case the contents and subject are the same but the headers are different,
in particular to all reply-to to go back to the appropriate alias.
I didn't see any option to affect which aspects of an email are used to determine sameness.
And yes, to keep the performance goals, I assume it is necessary to create hashes of the parts used for the comparison.

**Comment by eyalroz** [comment]
> I didn't see any option to affect which aspects of an email are used to determine sameness.

Ah, but it's right there...

* Under the button on the main toolbar which runs the dupe search (do "Customize Toolbar" if you don't have it).
* In the add-on's preferences dialog: Menu Bar | Tools | Add-On Preferences | Remove Duplicate Messages.

**Comment by RogerRiggs** [comment]
Ahhh... its there.  I looked in the Tools->AddOn Options->Remove Duplicate Options pane.
It was in the FAQ too, but not in the project doc. Sorry for the noise.

**Comment by eyalroz** [comment]
@RogerRiggs : It's not your fault really, it's the discrimination against regular add-ons. The current leadership of the project (which has actually done some pretty horrid things recently BTW) has an anti-extension bent. They're trying to pressure everyone to settle for crippled web-extensions rather than properly supporting continued loading regular extensions, access to their preferences etc. If things weren't this F'ed up, the preferences would have also been accessible from the add-ons pane.
