### ISSUE TITLE
It says it can search across folders, but how?!

### ISSUE THREAD

**Issue by johnstonesnow** [eyalroz/removedupes#209]
I have tons of email I've imported to TB after leaving Mac Mail behind. I have duplicates cross different folders. 
The plugin page says this plugin can find dupes across folders, but I can't find any instructions for how to do it. I wonder if it's related to TB's ongoing lack of ability to select multiple folders (ctrl-click or shift-click)?
If not, I'd be very grateful if someone could advise how to do this please

**Comment by johnstonesnow** [comment]
Thank you. I heard similar things recently. I guess I better take a look at BetterBird, which was suggested to me. If you have any thoughts on that, I'd sure appreciate hearing them :) 
thanks again
And BTW - I managed to use the tool to remove dupes manually on each folder, took a while. Wow, what a slick plugin, worked like a charm without any tweaks. Great work.

**Comment by eyalroz** [comment]
Betterbird is a patchset over Thunderbird, a project of - mostly - my friend Jorg Knobloch, who was one of the main developers and project board member for years. He was ousted a few years ago, essentially for being in opposition to the project's direction and the way it was being managed. They literally banned him from the project - to the level of having a filter which prevents messages mentioning his name from making it to the project discussion mailing list, at some point. It was crazy.

I like Betterbird - and in fact use instead of TB per se - but there is only so much Jorg can do over the baseline.

As for your experience - thanks for the compliment. removedupes is not such a magical piece of software, I worked out the main kinks of the dupe detection and removal logic over a decade ago; the extension was originally written in 2007, and since TB has not _added_ functionality which would allow me to improve on the extension's functionality, I've mostly been trying to keep up with TB and hop past the occasional obstacle. These days it's not so easy.

**Comment by johnstonesnow** [comment]
Excellent thank you. Yes, I have actually had some emails with Jörg. Wow. I also read the back and forth he had regarding the 'ban'. Reminded me of a phrase an old (now dead) friend used to say: "Give a small man power, and he'll show you how small he is." Seemed utterly tyrannical to me but that aside...

I don't care if he struggles to maintain it perfectly, he seems to be committed to doing his best for users and that's more than good enough for me. I'd sooner use, support, and donate to someone like that, than certain other types of people.

Thanks for the replies, BB for me, TB for the, er, trash bin. ha, i should be on stage. :D

**Comment by PackElend** [comment]
by the way, can you say, what is the last version, which allows you to select multiple folders? 
A Workaround could be to use this version only for finding dupes.
