### ISSUE TITLE
Large Folder ?

### ISSUE THREAD

**Issue by david-navigator** [eyalroz/removedupes#213]
I am trying to deduplicate a large folder (250,000 messages - 25GB).
In the status I see "Duplicate message search complete", but no dialog appears - even after maybe 10 minutes and I have to kill Thunderbird. 
I'll try leaving it running overnight, but I suspect the amount of duplicate messages is too overwhelming (I suspect each message exists 2 or 3 times as the folder emptied itself yesterday and after Thunderbird rebuilt it, it's now over twice as large as it was before.)
Any suggestions either to make the data more manageable or to debug why nothing is appearing ?

**Comment by eyalroz** [comment]
The question is probably more the number of dupe sets and their sizes rather than the number of messages. Also - whether it's an IMAP or POP3 folder; and whether or not you were using body comparison.

Anyway, to answer your question: Yes, there is: You can skip the dialog, and have the duplicate messages moved without confirmation to the target folder (typically the trash, but you can change that - it's a preference). Make sure you clear the target folder first, so that you can then examine what's been moved there.

To skip the review dialog, open the extension's preferences dialog, and uncheck "review search results before deletion".

**Comment by david-navigator** [comment]
Hi

That seems to have worked :)
250,000 messages reduced to 86,000. The one thing I notice is that the msf file is now 0 bytes - I can see that a system process has a file to it, so I'm guessing that it's being slowly rebuilt in the background somewhere, rather than me having to force a folder repair?

**Comment by eyalroz** [comment]
> so I'm guessing that it's being slowly rebuilt in the background somewhere, rather than me having to force a folder repair?

Maybe. TB is often finicky and brittle. It has nothing to do with my extension though - I just ask for files to be deleted or moved.
