### ISSUE TITLE
Crashing Thunderbird with large collection of E-Mails

### ISSUE THREAD

**Issue by Jurgster** [eyalroz/removedupes#219]
Hi,
So here is the config:
Thunderbird 115.11.1 (64-bit)
Remove Duplicate Messages Version 0.5.4b5

Apart from the fact that the scan requires over 24 hrs, once it has sorted and I say it can delete it does not take to long to crash Thunderbird. I will mention we are talking about a large collection of E-Mails, I am over 25k.
Maybe a status file would help with a pickup from crash situation to cut-out repeated start from the beginning?

Respect to the addon still.

**Comment by eyalroz** [comment]
That is quite weird. Many users typically scan 100 K messages and much more - within a minute. Is it possible that you are comparing bodies, and use very few other comparison criteria? Otherwise, there is something wrong going on with TB's access of the mail folders.

**Comment by Jurgster** [comment]
Hi,
General Settings:
Skip IMAP messages marked 'Deleted'
Search subfolders of selected top folder(s)
Review search results before deletion
Default action for duplicate messages:
Delete permanently

Message Comparison settings:
Author('From')
Recipients ('To')
CC List
Message ID
Send time
Subject

**Comment by eyalroz** [comment]
Weird... are your messages on an IMAP server? If so, can you try reproducing this

**Comment by Jurgster** [comment]
Hi,
Had a lot to do, so got back to trying to solve the hiccups.
Found out a probable reason why things are not working.
First disabled Review search results before deletion
things went considerably faster but it is still crashing most likely due to bad hashing / sorting / etc...
Screenshots will hopefully give the gist.
Before disabling Review search results before deletion:
![thunderbird hash mesages](https://github.com/eyalroz/removedupes/assets/118252/57b475f0-4015-4f26-9108-244aaa9ceecd)

![thunderbird hash mesages ergibnis](https://github.com/eyalroz/removedupes/assets/118252/2096a117-bfba-433a-bb6d-6431a5ec238f)
After:
![thunderbird hash mesages ergibnis folder](https://github.com/eyalroz/removedupes/assets/118252/6a23a86a-9562-4e3c-aedc-1f1104530145)
However the truth is the folder has:
![thunderbird hash mesages ergibnis folder wirklich](https://github.com/eyalroz/removedupes/assets/118252/5940a591-2cf7-4504-b687-21dc656af604)

Trying to repair bought nothing.

**Comment by eyalroz** [comment]
1. Can you verify the folder _and subfolders_ together only contain 95 messages?
2. Is that an IMAP folder?
3. If so, what happens when you copy that folder, with subfolders, into a local folder, and run a dupe search there?

Finally, I'll say that when you're seeing potentially-buggy behavior, I would recommend moving to trash or another folder rather than deleting permanently - to be on the safe side.

**Comment by Jurgster** [comment]
Local Folders Inbox/subfolder level1/subfolder level2
Inbox after filter empty with 15 subfolder leve1
subfolder level1 9 Messages and 10 subfolder level2
1)8 Messages
2)122 Messages 2 subfolders
3)given subfolder level2 with 95 Messages has 95 Messages and no further subfolder
4)4 Messages 3 subfolders
5)125 Messages
6)54 Messages
7)2480 Messages
8)44 Messages
9)122 Messages
10)1722 Messages 2 subfolders
I will stop at that there are many other subfolders.

As one can see no to IMAP

**Comment by eyalroz** [comment]
I'm sorry, but - even if it's not IMAP-related - this is a Thunderbird problem. Extensions can in principle fail - but not crash the app. And there are tens of thousands of people who have used the extension with large numbers of emails in many folders and have not experienced this crash. If you can provide instructions on how to reproduce this issue, I'll try to follow them; otherwise we'll close the bug, and I suggest you update your TB version and perhaps use a new profile.

**Comment by Jurgster** [comment]
Unfortunately not able to see at what point it crashes debugging seems problematic. I admit I am somewhat reluctant to start from scratch again with my E-Mails as there are so many at some point I will be forced to purge. Thankyou still for your attempts to help.
