### ISSUE TITLE
Check subject more intelligently

### ISSUE THREAD

**Issue by knulo** [eyalroz/removedupes#234]
FEATURE REQUEST:
It would be great if the subject check worked in such a way that two subjects were recognized as "the same" even if they only differ in one part (e.g. a term in square brackets - configurable with wildcards or regex at best). My provider flags spam using '[SPAM]', but an unflagged version is often still delivered.

**Comment by eyalroz** [comment]
I won't do that, because:

1. You're the first person to ask for this particular feature in about 15 years.
2. It is imperative that I err on the side of caution, and not relax comparison criteria like that: It is a million times better to fail to recognize dupes than to delete a single non-dupe email.

with that being said - if you want to implement a "comparison up to a canonicalizing regexp application" on various header fields, generically, and as an opt-in feature - I would entertain a PR of such a feature. Unfortunately, I doubt I'll have time in the near future to work on something like this.

**Comment by knulo** [comment]
Hi Eyal,
thank you for your quick reply. I understand your objections and will solve the "problem" differently.

**Comment by eyalroz** [comment]
Just so you know: The reason I don't have time to work on this is:

1. My day job...
2. My trying to be active against the war in Gaza
3. Other FOSS obligations, mainly LibreOffice
