### ISSUE TITLE
some comments

### ISSUE THREAD

**Issue by hopalongrock** [eyalroz/removedupes#25]
It works very well, but I have some comments.
A little bit funny for me, that in the window titled 'Duplicate messages Deletion" I check mark what I want to keep, and not what I want to delete.
Also, my default (but configurable) option and setting would be "Keep All Copies" and not "Keep First Copy" as it is now.
Maybe this default could be set in the dropdown menu under the Comparison Criteria.
I can't see where I clicked on the right side, all four keep options are equally gray, only the check marks change. 
This can be confusing in case of many lines, you have to look through every line what is check marked.
Therefore the use of mixed check marks could also be indicated, for example as "mixed copy"
Also, if all keep All copies is set, OK will not work.

**Comment by eyalroz** [comment]
Comments work better via email, but - ok.

>  funny for me, that in the window titled 'Duplicate messages Deletion" I check mark what I want to keep, and not what I want to delete.

Hmm. You make a good point about the ambiguity due to the dialog title. I should consider changing it.

> my default (but configurable) option and setting would be "Keep All Copies" and not "Keep First Copy" as it is now.
Maybe this default could be set in the dropdown menu under the Comparison Criteria.

You get this "for free" by simply not performing a dupe check... I've never once gotten someone asking me to allow for a "keep all" by default. If more users ask for it, I'll consider adding that as an option.

> I can't see where I clicked on the right side, all four keep options are equally gray, only the check marks change.

I don't understand quite what you mean. Can you open a separate issue about this, and attach a screenshot with explanatory text?

> Also, if all keep All copies is set, OK will not work.

If you keep all copies, what you're really doing is Cancel'ing the removal. So instead of doing that, just press Cancel. Although... I suppose I could accept a no-removal situation as well. Please open a separate issue about this.
