### ISSUE TITLE
No "Options" for addon

### ISSUE THREAD

**Issue by imThief** [eyalroz/removedupes#41]
Hello!
Cannot configure, because there is no "Options" page available for this add-on... Therefore it cannot find duplicates correctly, can you help?
![image](https://user-images.githubusercontent.com/39994745/106304178-1730db80-626c-11eb-9479-9862606519b1.png)

**Comment by imThief** [comment]
Found solution in the bug report #32 . I'll attach the picture - in case this can be useful for someone else...
Author, i recommend you to mention this moment somewhere - it is not clear understood from any docs/readme/overviews. Thanks!
![image](https://user-images.githubusercontent.com/39994745/106307760-cc659280-6270-11eb-9838-fd5cc5ee13ca.png)

**Comment by eyalroz** [comment]
This is happening because the Thunderbird developers are trying to strangle out regular extensions in favor of "web extensions", whose functionality is limited. Specifically, they are not willing to load a regular options dialog from an extension's entry in the Add-Ons page. If that sounds ridiculous - that's because it is. And the options dialog you see for some other extensions _cannot_ set usual Thunderbird preferences.
