### ISSUE TITLE
Not searching special folders.

### ISSUE THREAD

**Issue by bkarlan** [eyalroz/removedupes#45]
I'm trying to search for duplicates in an Archives folder with many sub-folders but I keep getting the message above "Not searching special folders".  This is not a search folder this is a regular folder in an email address called Archives.
![Screenshot from 2021-03-05 10-36-44](https://user-images.githubusercontent.com/2250480/110145173-c2b6d980-7d9e-11eb-9849-1d64d48647da.png)
Oddly, in another email address, searching the Archives and it's subfolders. works fine

**Comment by eyalroz** [comment]
"Archives" is considered a special folder. However, you can use the add-on options dialog to allow searching in special folders if you like. The dialog is accessible through the Tools menu on the main menu bar (which you should enable in case it's hidden.)

**Comment by bkarlan** [comment]
Thank you

**Comment by eyalroz** [comment]
Oh, I should also mention I've been banned from posting on all official Thunerderbird/Mozilla servers and mailing lists because of project politics. This will also hamper my ability to work on this issue.

**Comment by bkarlan** [comment]
I've left Apple, Google and Amazon due to those reasons.  I'm running Manjaro on my MB pro right now and as a non tech person the learning curve has been high but it is stable at this point.  I knew Mozilla leaned left but didn't know they were also banning conservatives.

**Comment by eyalroz** [comment]
> I knew Mozilla leaned left

I've never noticed them leaning left, except in the sense that FOSS might be considered a left-leaning endeavor.

>  but didn't know they were also banning conservatives.

Oh, I'm not a "conservative" (neither in the US or European sense); actually, I'm more of Anarchist. But that's not why I was banned. I was banned because of my criticizing the ruling clique on the TB council, criticizing censorship on project mailing lists, opposing secret in-abstentia trials (I was subjected to one naturally), the "code of conduct"-like document Thunderbird adopted after re-joining Mozilla which requires those, and in fact some election rigging.

**Comment by eyalroz** [comment]
Please reopen if this is still an issue (and please try this with a TB 91 profile).
