### ISSUE TITLE
Free disk space (compress folder) not working

### ISSUE THREAD

**Issue by sailor16** [eyalroz/removedupes#51]
Hi,

I successfully removed ("deleted") duplicates from a large folder (3.4 GB with mostly all mails being doubled).

But when I go forward to compressing that folder, nothing happens in effect (it should free roughly 1.7 GB of disk space). 
Calling "compress folder(s)" by right mouse-click on folder name or file menu does not make any difference.

"Remove duplicates" (from folder's right-click menu) does not show any remaining duplicates and the message listing does not display the duplicates any longer.

What is going wrong here?

BR,
Sailor

**Comment by eyalroz** [comment]
I can't say that I know what's going on. The TB storage backend is not the most robust technology... at least when its mbox-file-based. 

However - it is Not My Fault (TM) ... if you don't see any dupes in the folder, then my extension's job is done.

I should also mention that the removedupes extension does not itself do message movement/deletion - it only asks Thunderbird to perform a bulk-move / bulk delete.

So, please file a bug against Thunderbird at bugzilla.mozilla.org

Also, be advised that I have been banned from ever participating in the Thunderbird project, because of, and I quote "Disruptive Behavior, Heckling, Personal attacks, attacking someone for their ideas". In other words, I was critical of the ruling clique so they had me banned, following other political opponents. This means I will not even be able to comment on your bug report.

**Comment by sailor16** [comment]
Hi Eyalroz,

thank you for your comment.

In the end I managed to free the disk space by doing a folder-repair (folder > properties > repair) followed by a fresh "compact" call.

BR,
Sailor
