### ISSUE TITLE
Problem with deletions upon using this module

### ISSUE THREAD

**Issue by danielnicollet** [eyalroz/removedupes#64]
Hello, 

I tried to use this module with version 78.13.0 (64 bits) of Thunderbird.  The option was checked to avoid complete email deletion before I decide to go along with final deletion.  But it massively deleted my emails on an IMAP account with no prior move of messages to Trash box (more than 40k emails out of 57k).  My trash is empty.  See option as checked in settings :
![image](https://user-images.githubusercontent.com/3935614/131261447-c9c2cae2-59e6-4480-98e9-20a9f0630df0.png)

I also found that triggering the module from a right click on one folder, still sweeps and deletes messages from all folders. I can just imagine sorting through a mix of inbox messages and sent messages in trash.  Not very practical... Especially mith dozens of Inbox subfolders. 
Kind of real pain if you ask me to reload from backup over 150k email messages and folders....

Thanks,
Dan

**Comment by eyalroz** [comment]
First - please separate the issue of right-click triggering from the data-loss issue, since they are (probably) independent.

Now, what you're describing is very surprising to me, because this functionality has not changed for well over 10 years, and I've never received a complaint about data loss.

I'll ask you for several actions and bits of information:

* Please check other trash folders, in particular your Local Folders trash. Perhaps the messages were moved there?
* Is your Thunderbird session in which this happened still active? Assuming it is, please open the Error Console (with Ctrl+Shift+J or from Tools | Developer Tools | Error Console), and try to locate any possibly relevant messages or errors by the removedupes extension. If it is not still active:
    * Start TB.
    * Create an artificial dupe pair (e.g. copy the same message to a folder twice),
    * Open the Error Console
    * Clear the console (pressing the garbage bin button)
    * Run dupe removal
    * Make a screenshot or copy-paste any relevant new entries in the console.
* During the message removal - what was the TB status bar saying? Were you getting progress indication?
* Did the duplicate review dialog come up after the dupe search?

**Comment by danielnicollet** [comment]
Sadly, I have erased the profile and restarted from scratch. I will retest eventually maybe because I still need to re-run dedup at some point…

**Comment by eyalroz** [comment]
@danielnicollet : So, what about trying to reproduce this with your empty profile?

**Comment by eyalroz** [comment]
Anyway, it seems like my default behavior is indeed to move to the Local Folders' trash folder. So it's likely your messages were moved there.

**Comment by eyalroz** [comment]
I guess... it might be useful to have a third deletion option: "Move to account Trash folder", which would only be available if all dupes are from a single account.

**Comment by eyalroz** [comment]
Please have a look at #67 .
