### ISSUE TITLE
Feature request: dealing with read/unread status

### ISSUE THREAD

**Issue by bruvi** [eyalroz/removedupes#71]
Hi
I would very much appreciate if this extension could select which message to keep according to the read/unread status, or to adjust the read status of the kept message: if any version of the duplicate message is marked read, the kept message should be marked read. 

I had the bad habit of retrieving mail via pop and reading it on two machines, and roughly half of my messages are marked read on each one :-/. Now that I have fiber at home, I am switching to imap/self-hosting, and I'd like to merge both "poped" mailboxes, finding which messages I did never read...

Thanks !

**Comment by eyalroz** [comment]
This is actually already taken care of - indirectly: If you open the review dialog, enable the message flags column, and sort by that column, you'll notice that the IS_READ message always appears first, or always appears last (depending on the sort order). So, you choose "Keep First" or "Keep Last" as appropriate, and you only keep the read copies, or only keep the unread copies.

I suggest that, when doing this, you move the messages to trash rather than deleting them permanently, in case you get something wrong and want to undo the "deletion".

**Comment by bruvi** [comment]
I had not seen that there was an optional "Flags" column, with READ, HAS_ATTACHMENTS, REPLIED... 
Sorting duplicates according to this column works as you described and solved my problem !

Thanks a lot!
