### ISSUE TITLE
Thunderbird freezes when checking for mails

### ISSUE THREAD

**Issue by 0711master** [eyalroz/removedupes#98]
Since around two weeks ago every time that Thunderbird is checking for and downloading mails it freezes as long as the process is going on. When I deactivate the plugin it's behaving normal again.

**Comment by eyalroz** [comment]
The freeze is almost certainly unrelated to my extension, because the extension doesn't act on incoming mail, nor does it get called or triggered by mail arriving.

* Are you getting any relevant errors in the Developer Tools Error Console?
* Have you tried enabling the extension in a clean profile?

**Comment by 0711master** [comment]
I just checked, but no relevant errors. I didn't try it in a clean profile, because I don't want mails to be downloaded in another profile. But when I'm travelling I'm copying my whole profile on my laptop, so next time I will at least check if I have the same problem on my laptop.

**Comment by 0711master** [comment]
Ok, I have to revoke, now it also freezes with the plugin deactivated :(

**Comment by eyalroz** [comment]
I'm "glad" to hear that... try the Thunderbird IRC channels on libera.chat maybe.
