### ISSUE TITLE
no duplicates found

### ISSUE THREAD

**Issue by ms1222** [eyalroz/removedupes#99]
I'm using Thunderbird 102.3.0.  with gmail
I have Author, Send time, Size and Subject checked, with time Comparison Resolution "day"

I know there are many such duplicates.   One in particular is a google calendar invite sent to two different email addresses, both of which forward to me.  The only difference is the To field.

Any suggestions are appreciated.

Also,  In a previous deletion run I deleted.  They came out of my thunderbird inbox, but are still in my gmail inbox.   Any suggestions?  (I waited and also clicked Get messages so they would synch.   When I tried manually deleting a known duplicate, from within Thunderbird, gmail updated properly.

Thanks in advance.

**Comment by eyalroz** [comment]
These situations are (almost) always the result of slight differences which aren't noticeable when reading the message. For example - perhaps the sizes different by a few bytes here or there due to an extra newline?

I suggest gradually removing criteria until you start seeing duplicates, then adding criteria back to see which one makes the distinctions.

If this doesn't work, please check the error console (Tools | Developer Tools | Error Console) for errors which mention removedupes. It's better to first clear the console, then run a dupe search, then search the console to see what's been added.

**Comment by eyalroz** [comment]
Please reopen if my suggestion does not resolve your issue.

**Comment by peterhoult** [comment]
I love using this Add-On but sadly it doesn't seem to Find/Remove all duplicates.  I have Run the Add-On once in this folder and it did remove some Duplicates but I still see  more Duplicates.  Do you put a "marker" on a folder where this operation has been executed so that you can only Run it once?  I am using Thunderbird 102.4.0
![Screenshot (4)](https://user-images.githubusercontent.com/116595569/197614950-c8090f27-74c2-435d-a30c-2de916ce8ea3.png)
I have attached a screenshot as proof - they are identical emails that are highlighted in bold in the image

**Comment by eyalroz** [comment]
@peterhoult : 

1. It is almost certain that this is because the messages are _almost_ duplicates, e.g. they differ by a few extra empty lines or spaces, or a few seconds of send time etc. Start removing comparison criteria gradually until you catch them.
2.  If this is still a problem, please open a separate issue.
